### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by flaviode** [carlferr/HOME-BIO#1]
Hi there, 
I am trying to install Docker but it doesn't work. 
I am trying to use the preferred choice - from the repository - but at the It returns: 

"
sudo apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  aufs-tools cgroupfs-mount | cgroup-lite
The following NEW packages will be installed:
  containerd.io docker-ce docker-ce-cli
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/93.8 MB of archives.
After this operation, 426 MB of additional disk space will be used.
Selecting previously unselected package containerd.io.
(Reading database ... 146941 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.4.6-1_amd64.deb ...
Unpacking containerd.io (1.4.6-1) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a20.10.7~3-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-ce-cli (5:20.10.7~3-0~ubuntu-xenial) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../docker-ce_5%3a20.10.7~3-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-ce (5:20.10.7~3-0~ubuntu-xenial) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Processing triggers for systemd (229-4ubuntu21.31) ...
Setting up containerd.io (1.4.6-1) ...
Setting up docker-ce-cli (5:20.10.7~3-0~ubuntu-xenial) ...
Setting up docker-ce (5:20.10.7~3-0~ubuntu-xenial) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for systemd (229-4ubuntu21.31) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
flavio@LAPTOP-CJOFULMI:~$ sudo docker run hello-world
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
"

How can I figure out that issue?

Thanks

**Comment by BioH4z** [comment]
Dear user, this is just a common error generated from Docker after the first installation.
Try:
_systemctl start docker_
or
Reboot the system

For other approaches, we suggest to check the Docker online guide (https://docs.docker.com/) or forum.

Let us know if these solutions were effective.

Thanks for using HOME-BIO

**Comment by flaviode** [comment]
nope...
it is still not working

**Comment by BioH4z** [comment]
Dear user,
We are sorry that the suggested procedures were not effective.
We can only suggest other few approaches:

1) _sudo systemctl start docker_ after the rebooting
2) search similar issues on Docker forum or GitHub (searching online seems a very common one)
3) a new clean reinstallation of Docker (follow the online guide from Docker official website)
4) try Docker on Windows (our pipeline works also on Windows)

However, this is not an "issue with installation" of our pipeline (it doesn't need to be installed) but an issue with the Docker installation.
For this reason we strongly suggest to search for help on Docker official channels.

Thanks again for using HOME-BIO

**Comment by flaviode** [comment]
Hi there, 
finally, I am using the windows version and it seemed to work. However, I followed the instruction at all, Docker is ok (hello-world is fine), python is running, but when I type in HOME-BIO folder 

> python HOME_Bio_windows.py -c config_file.txt    #to launch the pipeline, it returns:

HOME-Bio
Sintassi del comando errata.
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

Can you help me?
Thanks

**Comment by BioH4z** [comment]
Dear User,
We are glad to know that you tried one of the proposed options.
We are sorry to hear that you still have issues.
We were able to replicate your problem.

We are trying to fix a python issue with the spaces on the paths on Windows.
Are are trying to run it on the Desktop?
Because "Documents and Settings" in the absolute path could create this issue.
We suggest to move all the folders necessary for the pipeline in a location without spaces in the path (e.g. "C:\\Users\").
Please avoid "Documents and settings" or "Program Files".

We are very sorry that we never saw this issue before.

Let us know if this worked or if there are other problems.

Thanks again for using HOME-BIO

**Comment by BioH4z** [comment]
Dear user,
We are happy to inform you that we fixed the issue.
Redownload HOME-Bio_windows.py and try to run the script from the HOME-BIO-master folder (wherever it is).

Let us know if it works in order to close the issue.

Thanks again for your patience and for using our pipeline

**Comment by flaviode** [comment]
Hi there, 
glad you fix the issue! indeed, I was working in System32 and it worked well!
1
however, I am trying to download the set database from zenodo but it seems to be challenging. 
is there an FTP connection for that task? 
Thanks

**Comment by BioH4z** [comment]
Dear user,
we are happy that worked. 

We are sorry to hear that you are having difficulties to download the database. Unfortunately, this is a very big database (about 200 GB compressed). We also found difficulties in downloading it again from Zenodo and we sent them an email complaining about that.

For this reason, I'm going to close this issue (that is solved) and I'm going to try to solve the issue about downloading the databases. We will let you know if we find a more convenient solution.

Meanwhile, we suggest to generate them from scratch following the steps suggested also in our tutorial.

For further comunications you can send an email directly to us: @BioH4z or @carlferr

Thanks again for using HOME-BIO
